// <auto-generated />
using System;
using Aplikasi_Apotek.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aplikasi_Apotek.Migrations
{
    [DbContext(typeof(ApotekContext))]
    [Migration("20240111065705_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Aplikasi_Apotek.Models.Barang", b =>
                {
                    b.Property<int>("Id_barang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_barang"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expired_date")
                        .HasColumnType("datetime2");

                    b.Property<long>("Harga_Satuan")
                        .HasColumnType("bigint");

                    b.Property<long>("Jumlah_barang")
                        .HasColumnType("bigint");

                    b.Property<string>("Kode_barang")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nama_barang")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Satuan")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id_barang");

                    b.ToTable("Barang");

                    b.HasData(
                        new
                        {
                            Id_barang = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Expired_date = new DateTime(2024, 1, 11, 13, 57, 2, 808, DateTimeKind.Local).AddTicks(1862),
                            Harga_Satuan = 75000L,
                            Jumlah_barang = 100L,
                            Kode_barang = "OBT",
                            Nama_barang = "Obat Tidur",
                            Satuan = "Pcs",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id_barang = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Expired_date = new DateTime(2024, 1, 11, 13, 57, 2, 808, DateTimeKind.Local).AddTicks(1891),
                            Harga_Satuan = 5000L,
                            Jumlah_barang = 50L,
                            Kode_barang = "OBT",
                            Nama_barang = "Obat Maag",
                            Satuan = "Pcs",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id_barang = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Expired_date = new DateTime(2024, 1, 11, 13, 57, 2, 808, DateTimeKind.Local).AddTicks(1895),
                            Harga_Satuan = 25000L,
                            Jumlah_barang = 15L,
                            Kode_barang = "OBT",
                            Nama_barang = "Obat Pilek",
                            Satuan = "Pcs",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Aplikasi_Apotek.Models.Log", b =>
                {
                    b.Property<int>("Id_log")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_log"));

                    b.Property<string>("Aktivitas")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_user")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Waktu")
                        .HasColumnType("datetime2");

                    b.HasKey("Id_log");

                    b.HasIndex("Id_user");

                    b.ToTable("Log");

                    b.HasData(
                        new
                        {
                            Id_log = 1,
                            Aktivitas = "Login",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id_user = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Waktu = new DateTime(2024, 1, 11, 13, 57, 2, 808, DateTimeKind.Local).AddTicks(4146)
                        },
                        new
                        {
                            Id_log = 2,
                            Aktivitas = "Logout",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id_user = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Waktu = new DateTime(2024, 1, 11, 13, 57, 2, 808, DateTimeKind.Local).AddTicks(4154)
                        },
                        new
                        {
                            Id_log = 3,
                            Aktivitas = "Login",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id_user = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Waktu = new DateTime(2024, 1, 11, 13, 57, 2, 808, DateTimeKind.Local).AddTicks(4156)
                        });
                });

            modelBuilder.Entity("Aplikasi_Apotek.Models.Transaksi", b =>
                {
                    b.Property<int>("Id_transaksi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_transaksi"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_barang")
                        .HasColumnType("int");

                    b.Property<int>("Id_user")
                        .HasColumnType("int");

                    b.Property<string>("No_transaksi")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("Tgl_transaksi")
                        .HasColumnType("datetime2");

                    b.Property<long>("Total_bayar")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id_transaksi");

                    b.HasIndex("Id_barang");

                    b.HasIndex("Id_user");

                    b.ToTable("Transaksi");

                    b.HasData(
                        new
                        {
                            Id_transaksi = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id_barang = 3,
                            Id_user = 1,
                            No_transaksi = "001",
                            Tgl_transaksi = new DateTime(2024, 1, 11, 13, 57, 2, 808, DateTimeKind.Local).AddTicks(3549),
                            Total_bayar = 25000L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id_transaksi = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id_barang = 3,
                            Id_user = 1,
                            No_transaksi = "002",
                            Tgl_transaksi = new DateTime(2024, 1, 11, 13, 57, 2, 808, DateTimeKind.Local).AddTicks(3561),
                            Total_bayar = 25000L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id_transaksi = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id_barang = 3,
                            Id_user = 1,
                            No_transaksi = "003",
                            Tgl_transaksi = new DateTime(2024, 1, 11, 13, 57, 2, 808, DateTimeKind.Local).AddTicks(3564),
                            Total_bayar = 25000L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Aplikasi_Apotek.Models.User", b =>
                {
                    b.Property<int>("Id_user")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_user"));

                    b.Property<string>("Alamat")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Telpon")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Tipe_user")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id_user");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id_user = 1,
                            Alamat = "JL Delima 1",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nama = "Lumi",
                            Password = "Mysql@2023",
                            Telpon = "081288531636",
                            Tipe_user = "Admin",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "lumi07"
                        },
                        new
                        {
                            Id_user = 2,
                            Alamat = "JL Mangga 1",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nama = "Novry",
                            Telpon = "081244542479",
                            Tipe_user = "Kasir",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "novry11"
                        },
                        new
                        {
                            Id_user = 3,
                            Alamat = "JL Apel 1",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nama = "Mekel",
                            Telpon = "089524790987",
                            Tipe_user = "Kasir",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "mekel2005"
                        });
                });

            modelBuilder.Entity("Aplikasi_Apotek.Models.Log", b =>
                {
                    b.HasOne("Aplikasi_Apotek.Models.User", "Users")
                        .WithMany()
                        .HasForeignKey("Id_user")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Aplikasi_Apotek.Models.Transaksi", b =>
                {
                    b.HasOne("Aplikasi_Apotek.Models.Barang", "Barangs")
                        .WithMany()
                        .HasForeignKey("Id_barang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aplikasi_Apotek.Models.User", "Users")
                        .WithMany()
                        .HasForeignKey("Id_user")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barangs");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
